# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Style/Encoding:
  Enabled: true
  
Metrics/LineLength:
  Max: 132
  


